# Generated by Django 6.1.1 on 2026-09-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('AIRTIME', 'Airtime'), ('DATA', 'Data'), ('CABLE', 'Cable TV'), ('ELECTRICITY', 'Electricity')], max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_tier',
            field=models.CharField(choices=[('REGULAR', 'Regular User'), ('RESELLER', 'Reseller'), ('API_USER', 'API Partner')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(choices=[('WALLET_FUNDING', 'Wallet Funding'), ('AIRTIME', 'Airtime'), ('DATA', 'Data'), ('CABLE', 'Cable TV'), ('ELECTRICITY', 'Electricity')], default='WALLET_FUNDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_code', models.CharField(max_length=50, unique=True)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_regular', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_reseller', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.serviceprovider')),
            ],
        ),
    ]
